-- V10: item-level returns (docs/design/09-returns-refunds.md) and the refund -> return link deferred from V7.
CREATE TABLE return_requests (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       BIGINT       NOT NULL,
    customer_id    BIGINT       NOT NULL,
    warehouse_id   BIGINT       NOT NULL,
    status         VARCHAR(30)  NOT NULL,
    reason         VARCHAR(500) NOT NULL,
    decision_note  VARCHAR(500),
    decided_by     BIGINT,
    decided_at     TIMESTAMP WITH TIME ZONE,
    received_by    BIGINT,
    received_at    TIMESTAMP WITH TIME ZONE,
    refund_amount  NUMERIC(12,2),
    version        BIGINT       NOT NULL DEFAULT 0,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_return_requests_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_return_requests_customer FOREIGN KEY (customer_id) REFERENCES users (id),
    CONSTRAINT fk_return_requests_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT ck_return_requests_status CHECK (status IN ('REQUESTED', 'APPROVED', 'REJECTED', 'REFUNDED'))
);

CREATE INDEX idx_return_requests_order ON return_requests (order_id);
CREATE INDEX idx_return_requests_customer ON return_requests (customer_id);
CREATE INDEX idx_return_requests_warehouse_status ON return_requests (warehouse_id, status);

CREATE TABLE return_items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_request_id BIGINT NOT NULL,
    order_item_id     BIGINT NOT NULL,
    quantity          INT    NOT NULL,
    restock           BOOLEAN,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_return_items_request FOREIGN KEY (return_request_id) REFERENCES return_requests (id),
    CONSTRAINT fk_return_items_order_item FOREIGN KEY (order_item_id) REFERENCES order_items (id),
    CONSTRAINT ck_return_items_quantity CHECK (quantity > 0)
);

CREATE INDEX idx_return_items_order_item ON return_items (order_item_id);

ALTER TABLE refunds ADD COLUMN return_request_id BIGINT;
ALTER TABLE refunds ADD CONSTRAINT fk_refunds_return_request FOREIGN KEY (return_request_id) REFERENCES return_requests (id);
