-- V4: warehouses, inventory, movement ledger (docs/design/02-domain-model.md, 05-inventory-concurrency.md).
CREATE TABLE warehouses (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(20)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    city        VARCHAR(100) NOT NULL,
    priority    INT          NOT NULL DEFAULT 100,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_warehouses_code UNIQUE (code)
);

CREATE INDEX idx_warehouses_priority ON warehouses (priority, id);

-- Deferred from V2: staff users belong to one warehouse.
ALTER TABLE users ADD CONSTRAINT fk_users_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id);

CREATE TABLE inventory (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          BIGINT NOT NULL,
    warehouse_id        BIGINT NOT NULL,
    on_hand             INT    NOT NULL DEFAULT 0,
    reserved            INT    NOT NULL DEFAULT 0,
    low_stock_threshold INT    NOT NULL DEFAULT 5,
    version             BIGINT NOT NULL DEFAULT 0,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_inventory_product_warehouse UNIQUE (product_id, warehouse_id),
    CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_inventory_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT ck_inventory_on_hand CHECK (on_hand >= 0),
    CONSTRAINT ck_inventory_reserved CHECK (reserved >= 0),
    -- The DB-level no-oversell safety net (doc 05).
    CONSTRAINT ck_inventory_reserved_le_on_hand CHECK (reserved <= on_hand)
);

CREATE INDEX idx_inventory_warehouse_id ON inventory (warehouse_id);

CREATE TABLE inventory_movements (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      BIGINT       NOT NULL,
    warehouse_id    BIGINT       NOT NULL,
    type            VARCHAR(30)  NOT NULL,
    quantity        INT          NOT NULL,
    reference_type  VARCHAR(30)  NOT NULL,
    reference_id    BIGINT,
    reason          VARCHAR(255),
    actor_id        BIGINT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_movements_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_movements_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT ck_movements_type CHECK (type IN
        ('STOCK_IN', 'ADJUSTMENT', 'RESERVE', 'RELEASE', 'PACK_DEDUCT', 'CANCEL_RESTOCK', 'RETURN_RESTOCK')),
    CONSTRAINT ck_movements_reference_type CHECK (reference_type IN ('ORDER', 'SHIPMENT', 'RETURN', 'MANUAL'))
);

CREATE INDEX idx_movements_product_warehouse ON inventory_movements (product_id, warehouse_id);
CREATE INDEX idx_movements_reference ON inventory_movements (reference_type, reference_id);
