-- V6: coupons and their redemptions (docs/design/02-domain-model.md, 08-pricing-discounts-tax.md).
CREATE TABLE coupons (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(40)   NOT NULL,
    description         VARCHAR(255),
    discount_type       VARCHAR(20)   NOT NULL,
    discount_value      NUMERIC(12,2) NOT NULL,
    max_discount        NUMERIC(12,2),
    min_order_amount    NUMERIC(12,2) NOT NULL DEFAULT 0,
    category_id         BIGINT,
    valid_from          TIMESTAMP WITH TIME ZONE NOT NULL,
    valid_to            TIMESTAMP WITH TIME ZONE NOT NULL,
    usage_limit         INT,
    per_customer_limit  INT           NOT NULL DEFAULT 1,
    used_count          INT           NOT NULL DEFAULT 0,
    active              BOOLEAN       NOT NULL DEFAULT TRUE,
    version             BIGINT        NOT NULL DEFAULT 0,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_coupons_code UNIQUE (code),
    CONSTRAINT fk_coupons_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT ck_coupons_discount_type CHECK (discount_type IN ('PERCENTAGE', 'FLAT')),
    CONSTRAINT ck_coupons_discount_value CHECK (discount_value > 0),
    CONSTRAINT ck_coupons_validity CHECK (valid_from < valid_to),
    CONSTRAINT ck_coupons_used_count CHECK (used_count >= 0)
);

CREATE INDEX idx_coupons_active ON coupons (active);

-- order_id references orders, which is created in V7 (the FK is added there).
CREATE TABLE coupon_redemptions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id   BIGINT  NOT NULL,
    customer_id BIGINT  NOT NULL,
    order_id    BIGINT  NOT NULL,
    released    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_coupon_redemptions_order UNIQUE (order_id),
    CONSTRAINT fk_coupon_redemptions_coupon FOREIGN KEY (coupon_id) REFERENCES coupons (id),
    CONSTRAINT fk_coupon_redemptions_customer FOREIGN KEY (customer_id) REFERENCES users (id)
);

CREATE INDEX idx_coupon_redemptions_coupon_customer ON coupon_redemptions (coupon_id, customer_id, released);
