-- V7: orders, order lines with allocations, status history, payments and refunds
-- (docs/design/02-domain-model.md, 04-order-state-machine.md, 06-checkout-and-payment.md).
CREATE TABLE orders (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number     VARCHAR(30)   NOT NULL,
    customer_id      BIGINT        NOT NULL,
    status           VARCHAR(30)   NOT NULL,
    subtotal         NUMERIC(12,2) NOT NULL,
    discount_total   NUMERIC(12,2) NOT NULL,
    tax_total        NUMERIC(12,2) NOT NULL,
    grand_total      NUMERIC(12,2) NOT NULL,
    coupon_code      VARCHAR(40),
    ship_name        VARCHAR(150)  NOT NULL,
    ship_line1       VARCHAR(255)  NOT NULL,
    ship_line2       VARCHAR(255),
    ship_city        VARCHAR(100)  NOT NULL,
    ship_state       VARCHAR(100)  NOT NULL,
    ship_pincode     VARCHAR(6)    NOT NULL,
    ship_phone       VARCHAR(10)   NOT NULL,
    idempotency_key  VARCHAR(100)  NOT NULL,
    placed_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    delivered_at     TIMESTAMP WITH TIME ZONE,
    cancelled_at     TIMESTAMP WITH TIME ZONE,
    version          BIGINT        NOT NULL DEFAULT 0,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_orders_number UNIQUE (order_number),
    CONSTRAINT uk_orders_customer_idempotency UNIQUE (customer_id, idempotency_key),
    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES users (id),
    CONSTRAINT ck_orders_status CHECK (status IN
        ('PLACED', 'CONFIRMED', 'PACKED', 'SHIPPED', 'DELIVERED', 'PARTIALLY_RETURNED', 'RETURNED', 'CANCELLED'))
);

CREATE INDEX idx_orders_customer_placed ON orders (customer_id, placed_at);
CREATE INDEX idx_orders_status ON orders (status);

CREATE TABLE order_items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          BIGINT        NOT NULL,
    product_id        BIGINT        NOT NULL,
    sku               VARCHAR(64)   NOT NULL,
    product_name      VARCHAR(200)  NOT NULL,
    unit_price        NUMERIC(12,2) NOT NULL,
    tax_rate          NUMERIC(5,2)  NOT NULL,
    quantity          INT           NOT NULL,
    line_subtotal     NUMERIC(12,2) NOT NULL,
    line_discount     NUMERIC(12,2) NOT NULL,
    line_tax          NUMERIC(12,2) NOT NULL,
    line_total        NUMERIC(12,2) NOT NULL,
    returned_quantity INT           NOT NULL DEFAULT 0,
    refunded_amount   NUMERIC(12,2) NOT NULL DEFAULT 0,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT ck_order_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_order_items_returned CHECK (returned_quantity >= 0 AND returned_quantity <= quantity),
    CONSTRAINT ck_order_items_refunded CHECK (refunded_amount >= 0 AND refunded_amount <= line_total)
);

CREATE INDEX idx_order_items_order_id ON order_items (order_id);
CREATE INDEX idx_order_items_product_id ON order_items (product_id);

-- Where each reserved unit came from: the source of truth for release / restock / routing.
CREATE TABLE order_item_allocations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id BIGINT NOT NULL,
    warehouse_id  BIGINT NOT NULL,
    quantity      INT    NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_allocations_item_warehouse UNIQUE (order_item_id, warehouse_id),
    CONSTRAINT fk_allocations_item FOREIGN KEY (order_item_id) REFERENCES order_items (id),
    CONSTRAINT fk_allocations_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT ck_allocations_quantity CHECK (quantity > 0)
);

CREATE INDEX idx_allocations_warehouse_id ON order_item_allocations (warehouse_id);

CREATE TABLE order_status_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT      NOT NULL,
    from_status VARCHAR(30),
    to_status   VARCHAR(30) NOT NULL,
    actor_id    BIGINT,
    note        VARCHAR(500),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_status_history_order FOREIGN KEY (order_id) REFERENCES orders (id)
);

CREATE INDEX idx_status_history_order_id ON order_status_history (order_id);

CREATE TABLE payments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT        NOT NULL,
    amount          NUMERIC(12,2) NOT NULL,
    method          VARCHAR(20)   NOT NULL,
    status          VARCHAR(20)   NOT NULL,
    transaction_ref VARCHAR(64)   NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_payments_order UNIQUE (order_id),
    CONSTRAINT uk_payments_transaction_ref UNIQUE (transaction_ref),
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_payments_amount CHECK (amount >= 0)
);

-- return_request_id and its FK are added in V10 with the returns tables.
CREATE TABLE refunds (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id      BIGINT        NOT NULL,
    order_id        BIGINT        NOT NULL,
    amount          NUMERIC(12,2) NOT NULL,
    reason          VARCHAR(20)   NOT NULL,
    status          VARCHAR(20)   NOT NULL,
    transaction_ref VARCHAR(64)   NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_refunds_transaction_ref UNIQUE (transaction_ref),
    CONSTRAINT fk_refunds_payment FOREIGN KEY (payment_id) REFERENCES payments (id),
    CONSTRAINT fk_refunds_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_refunds_amount CHECK (amount > 0),
    CONSTRAINT ck_refunds_reason CHECK (reason IN ('CANCELLATION', 'RETURN'))
);

CREATE INDEX idx_refunds_order_id ON refunds (order_id);

-- Deferred from V6.
ALTER TABLE coupon_redemptions ADD CONSTRAINT fk_coupon_redemptions_order FOREIGN KEY (order_id) REFERENCES orders (id);
