-- V8: one shipment per (order, warehouse), created by the async routing listener (docs 04, 07).
CREATE TABLE shipments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT      NOT NULL,
    warehouse_id    BIGINT      NOT NULL,
    status          VARCHAR(30) NOT NULL,
    tracking_number VARCHAR(100),
    packed_at       TIMESTAMP WITH TIME ZONE,
    shipped_at      TIMESTAMP WITH TIME ZONE,
    delivered_at    TIMESTAMP WITH TIME ZONE,
    version         BIGINT      NOT NULL DEFAULT 0,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    -- makes routing idempotent even if the listener ran twice
    CONSTRAINT uk_shipments_order_warehouse UNIQUE (order_id, warehouse_id),
    CONSTRAINT fk_shipments_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_shipments_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouses (id),
    CONSTRAINT ck_shipments_status CHECK (status IN ('PENDING', 'PACKED', 'SHIPPED', 'DELIVERED', 'CANCELLED'))
);

CREATE INDEX idx_shipments_warehouse_status ON shipments (warehouse_id, status);

CREATE TABLE shipment_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id   BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    quantity      INT    NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_shipment_items_shipment FOREIGN KEY (shipment_id) REFERENCES shipments (id),
    CONSTRAINT fk_shipment_items_order_item FOREIGN KEY (order_item_id) REFERENCES order_items (id),
    CONSTRAINT ck_shipment_items_quantity CHECK (quantity > 0)
);

CREATE INDEX idx_shipment_items_shipment_id ON shipment_items (shipment_id);
